name: Java CI with CloudSim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile Java files
      run: |
        mkdir classes
        javac -cp "lib/*" -d classes src/mysim/*.java

    - name: Run Simulation
      run: |
        java -cp "classes:lib/*" mysim.MySimulation
